### ISSUE TITLE
Typo in "Installing Tooling" section

### ISSUE THREAD

**Issue by slonik-az** [fedir/go-tooling-cheat-sheet#1]
Currently under _"Installing Tooling -> Easiest Way"_ it says (note the double-dot '..'):  
`$ go get -u golang.org/x/tools/..` 

I think it should end in triple-dots as follows:  
`$ go get -u golang.org/x/tools/...` 

Thanks,
--Leo

**Comment by fedir** [comment]
TRhank Leo ! Pushed in https://github.com/fedir/go-tooling-cheat-sheet/commit/7612d0ba83c697b9248cdc394501d14da5ed92e7
